//TIP To <b>Run</b> code, press <shortcut actionId="Run"/> or
// click the <icon src="AllIcons.Actions.Execute"/> icon in the gutter.
public class Main {
    public static void main(String[] args) {
        int a = 90125;
        System.out.println(a);
        byte b = 100;
        System.out.println(b);
        short c = 30000;
        System.out.println(c);
        long d = 30l;
        System.out.println(d);
        float e = 3.40f;
        System.out.println(e);
        double f = 10.15f;
        System.out.println(f);

        System.out.println("Задача 2");
        int g = 27897;
        System.out.println("Значение переменной g " + g);
        byte j = 67;
        System.out.println("Значенеи переменной j " + j);
        short p = 569;
        System.out.println("Значаение переменной p " + p);
        long m = 987678965549L;
        System.out.println("Значенеи переменной m " + m);
        float t = 27.12f;
        System.out.println("Значение переменной t " + t);
        double u = 2.786;
        System.out.println("Значение переменной u " + u);
        short w = -159;
        System.out.println("Значние переменной w " + w);

        System.out.println("Задача 3");
        short paper = 480;
        System.out.println("Лисвтов бумаги " + paper);
        byte pavlovna = 23;
        System.out.println("Учеников у Павловны " + pavlovna);
        byte sergeevna = 27;
        System.out.println("Учеников у Сергеевны " + sergeevna);
        byte andreevna = 30;
        System.out.println("Учеников у Андреевны " + andreevna);
        int total = pavlovna + sergeevna + andreevna;
        int totalNumber = paper / total;
        System.out.println("На каждого ученика рассчитано " + totalNumber + " Лисирв бумаги");

        System.out.println("Задача 4");
        byte bottleMakingMachinePerformance1 = 16;
        byte bottleMakingMachinePerformance = 16/2;
        System.out.println("За 1 минуту произвела машина " + bottleMakingMachinePerformance + " штук бутылок");
        byte time = 20;
        int productivityIn20Minutes = bottleMakingMachinePerformance * time;
        System.out.println("За 20 минут произвела машина " + productivityIn20Minutes + " штук бутылок");
        int time2 = 1440;
        int productivityIn1440Minutes = bottleMakingMachinePerformance * time2;
        System.out.println("За 1440 минуты в сутки произвела машина " + productivityIn1440Minutes + " шиук бутылок");
        int time3 = 1440 * 3;
        int productivityIn4320Minutes = bottleMakingMachinePerformance * time3;
        System.out.println("За 4320 муниуты в сутки произвела машина " + productivityIn4320Minutes + " штук бутылок");
        int time4 = 1440 * 30;
        int productivityIn43200Minutes = bottleMakingMachinePerformance * time4;
        System.out.println("За 43200 минуты в сутки произвела машина " + productivityIn43200Minutes + " штук бутылок");

        System.out.println("Задача 5");
        byte cansOfPaint = 120;
        System.out.println("банок краски " + cansOfPaint);
        byte cansOfWhite = 2;
        System.out.println("Белой краски " + cansOfWhite);
        byte cansOfBrown = 4;
        System.out.println("Коричневой крски " + cansOfBrown);
        int classes = cansOfWhite + cansOfBrown;
        System.out.println("Всего баок " + classes);
        int classes1 = cansOfPaint / classes;
        System.out.println("Количество класов " + classes1);
        int whitePaint = classes1 * cansOfWhite;
        int brownPaint = classes1 * cansOfBrown;
        System.out.println("В шокле, где " + classes1 + " классов, нужно " + whitePaint + " банок белой краски и " + brownPaint + " банок коричневой краски ");

        System.out.println("Задание 6");
        byte bananas = 5;
        System.out.println("Бананов " + bananas);
        byte gramsBanana = 80;
        System.out.println("Грамов банан " + gramsBanana);
        short milk = 200;
        System.out.println("Молоко " + milk);
        byte gramsMilk = 105;
        System.out.println("Грамм молока " + gramsMilk);
        byte iceCreamSundae = 2;
        System.out.println("брикеты " + iceCreamSundae);
        byte gramsIceCream = 100;
        System.out.println("Грамм мороженго " + gramsIceCream);
        byte rawEggs = 4;
        System.out.println("Сырые яйца " + rawEggs);
        byte egg = 70;
        System.out.println("Грамм яйцо " + egg);
        int fiveBananas = bananas * gramsBanana;
        System.out.println("Бананов надо " + fiveBananas + " граммов");
        int iNeedSomeMilk = milk * gramsMilk;
        System.out.println("Молока надо " + iNeedSomeMilk + " граммов");
        int in2Biscuits = iceCreamSundae * gramsIceCream;
        System.out.println("Надо мороженго " + in2Biscuits + " граммов");
        int in4Eggs = rawEggs * egg;
        System.out.println("Надо яиц " + in4Eggs + " граммов");
        int totalNumberOfGrams = fiveBananas + iNeedSomeMilk + in2Biscuits + in4Eggs;
        System.out.println("Общее " + totalNumberOfGrams + " граммов");
        float totalKg = 21.88f;
        float sportsEquipment = totalNumberOfGrams / totalKg;
        System.out.println("Вес спорт завтрака " + totalNumberOfGrams + " граммов");
        System.out.println("Вес спорт завтрака " + sportsEquipment + " килограммов");

        System.out.println("Задача 7");
        byte needToReset = 7;
        System.out.println("Нужно сбросить " + needToReset + " кг!");
        short loseWeight = 250;
        System.out.println("В день по " + loseWeight + " граммов");
        short loseTwoPounds = 500;
        System.out.println("В день по " + loseTwoPounds + " граммов");
        short inKgGrams = 1000;
        System.out.println("В килограме грамов " + inKgGrams);
        short theTotalWeightShouldBe = 7 * 1000;
        System.out.println("За 7 дней " + theTotalWeightShouldBe + " граммов");
        int gramsPerDay1 = theTotalWeightShouldBe / loseWeight;
        int gramsPerDay2 = theTotalWeightShouldBe / loseTwoPounds;
        System.out.println("Граммов уйдёт по 250 за каждый день " + gramsPerDay1);
        System.out.println("Граммво уйдёт по 500 за каждый день " + gramsPerDay2);
        int commonDays = gramsPerDay1 + gramsPerDay2;
        System.out.println("Общие дни " + commonDays);
        byte workout = 2;
        int averageDays = commonDays / workout;
        System.out.println("В среднем " + averageDays);

        System.out.println("Задача 8");
        int mashaGets = 67760;
        int denisGets = 83690;
        int kristinaGets = 76230;
        float increaseSalary = 10/100f;
        System.out.println("на 10% увелично " + increaseSalary);
        float raisingSalaries1 = mashaGets * increaseSalary;
        System.out.println("Зарплата Маши  будет на " + raisingSalaries1 + " рублей");
        float raisingSalaries2 = denisGets * increaseSalary;
        System.out.println("Зарплата Дениса будет на " + raisingSalaries2 + " рублей");
        float raisingSalaries3 = kristinaGets * increaseSalary;
        System.out.println("Зарплата Кристины будет на " + raisingSalaries3 + " рублей");
        float monthlySalaryMasha = mashaGets + raisingSalaries1;
        System.out.println("Месячная зп Маши " + monthlySalaryMasha + " рублей");
        float monthlySalaryDenis = denisGets + raisingSalaries2;
        System.out.println("Месячная зп Дениса " + monthlySalaryDenis + " рублей");
        float monthlySalaryKristina = kristinaGets + raisingSalaries3;
        System.out.println("Месячная зп Кристины " + monthlySalaryKristina + " рублей");
        byte month = 12;
        double annualSalaryMasha = monthlySalaryMasha * month;
        System.out.println("Годовая зарплата Маши " + annualSalaryMasha + " рублей");
        double annualSalaryDeins = monthlySalaryDenis * month;
        System.out.println("Годовая зарплата Дениса " + annualSalaryDeins + " рублей");
        double annualSalaryKristina = monthlySalaryKristina * month;
        System.out.println("Годовая зарплата Кристины " + annualSalaryKristina + " рублей");

    }
}